#网关服务端口号
server:
  port: 80
#网关服务ID 集群部署时必须一致
spring:
  application:
    name: zuul-gateway-server
eureka:
  instance: 
    #注册中心ip地址
    hostname: 127.0.0.1
  client:
    service-url:
      #注册地址
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    #因为本机即是注册中心所在机器 是否需要将自己注册到注册中心上 集群时 则为true
    register-with-eureka: true
    #因为本机即是注册中心所在机器 不需要去检索服务信息 集群时 则为true
    fetch-registry: true

###设置Feign超时时间
ribbon: 
  eureka: 
    # 关闭feign客户端的ribbon负载均衡器
    enabled: true 
  #指建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  #指建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000  
  
zuul: 
   host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
   routes: 
      #定义转发服务规则
      api-member: 
         #客户端请求127.0.0.1:80/api-member开头的 则转发到会员服务
         path: /api-member/**
         serviceid: api-member-server
      #定义转发服务规则
      api-order: 
         #客户端请求127.0.0.1:80/api-order开头的 则转发到订单服务
         path: /api-order/**
         serviceid: api-order-server
     
      